version: '3.5'

services:

  zookeeper:
    container_name: zookeeper
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    container_name: kafka
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override message.max.bytes=4000000 --override default.replication.factor=$${KAFKA_DEFAULT_REPL_FACTOR} --override num.partitions=$${KAFKA_NUM_PARTITIONS} --override delete.topic.enable=true --override group.min.session.timeout.ms=$${KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "storage-topic:1:1:compact,global-id-topic:1:1:compact,input-topic:1:1:compact,logx-topic:1:1:compact,dbx-topic:1:1:compact"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPL_FACTOR: 1
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 100

  materialize:
    image: "quay.io/eformat/materialize-pod:latest"
    ports:
      - "6875:6875"
    hostname: materalize
    volumes:
    - /home/mike/mzdata:/work/mzdata:Z
    network_mode: host
